### PR TITLE
Fix ruby 2.2 warning

### PR DESCRIPTION
**Pull request by diclophis**
This is all good changes

### CODE REVIEW

**Comment by diclophis** [comment]
@smtlaissezfaire have you had a chance to consider these changes?

**Comment by diclophis** [comment]
Ok, let me re-bake my PR to only include the stuff i need for the ruby 2.x support

**Comment by diclophis** [comment]
@smtlaissezfaire Thanks for pulling the framework forward outside of this PR. I am going to close this... it looks like the current version is better supported on ruby2.7

**Comment by smtlaissezfaire** [comment]
Thanks @diclophis.  

I know I had to upgrade it for a recent project but it still has some rough edges around rails...

**Pull request closed without merging**
